baseURL = 'https://dulce-van-vliet.github.io/'
languageCode = 'en-us'
title = 'Dulce van Vliet'
theme = 'PaperMod'

[params]
  description = "Academic research and publications"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowSocialIcons = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowRssButtonInSectionTermList = false
  ShowToc = false
  TocOpen = false

  [params.homeInfoParams]

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/dulcegoncalves/"

  [[params.socialIcons]]
    name = "email"
    url = "mailto:d.m.van.vliet@tue.nl"

  [[params.socialIcons]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?user=sJUJJUYAAAAJ&hl"

  [[params.socialIcons]]
    name = "orcid"
    url = "https://orcid.org/0000-0002-5467-7610"
    

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20

  [[menu.main]]
    identifier = "conferences"
    name = "Conferences"
    url = "/conferences/"
    weight = 30

  [[menu.main]]
    identifier = "data-vis"
    name = "Data & Vis"
    url = "/data-vis/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
