baseURL = 'https://dulce-van-vliet.github.io/'
languageCode = 'en-us'
title = 'Dulce van Vliet'
theme = 'PaperMod'

[params]
  description = "Academic research and publications"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = false
  ShowCodeCopyButtons = false
  ShowRssButtonInSectionTermList = false
  ShowToc = false
  TocOpen = false


[menu]
  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/publications/"
    weight = 20

  [[menu.main]]
    identifier = "conferences"
    name = "Conferences"
    url = "/conferences/"
    weight = 30

  [[menu.main]]
    identifier = "data-vis"
    name = "Data & Vis"
    url = "/data-vis/"
    weight = 40

[outputs]
  home = ["HTML", "RSS", "JSON"]
